### ISSUE TITLE
将 mModel = TUtil.getT(this, 1); 强转时出错

### ISSUE THREAD

**Issue by oh2080** [xiaoxiangyeyuHeaven/HeavenlyModule#6]
Caused by: java.lang.ClassCastException: java.lang.Object cannot be cast to com.ebensz.account.base.BaseModel
                                                       at com.ebensz.account.base.BaseActivity.onCreate(BaseActivity.java:77)
                                                       at android.app.Activity.performCreate(Activity.java:6727)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)

**Comment by oh2080** [comment]
在classpath 'com.android.tools.build:gradle:2.3.3 是正常的 ，当升级到  classpath 'com.android.tools.build:gradle:3.0.0-beta6 才会出错
